<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rst</string>
		<string>rest</string>
		<string>txt</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Sphinx Doc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^((?:=|\-|_|~|`|#|"|\^|\+|\*){3,})$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.doctitle.underline.sphinx</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.doctitle.sphinx.doc</string>
			<key>end</key>
			<string>^(\1)$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.doctitle.underline.sphinx</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#headings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([ \t]*)(?=\S)</string>
			<key>contentName</key>
			<string>meta.paragraph.sphinx.doc</string>
			<key>end</key>
			<string>^(?!\1(?=\S))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#links</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\.\.)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>comment</string>
					<key>end</key>
					<string>^(?!\s)</string>
					<key>name</key>
					<string>comment.block.double-dot.sphinx.doc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\.\.)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>comment</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-dot.sphinx.doc</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^([ \t]*)((\.\.)\sraw(::)) (html)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.directive.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.sphinx.doc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.other.directive.argument.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>directives.html</string>
					<key>end</key>
					<string>^(?!\1[ \t])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.punctuation.definition.directive.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.directive.name.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.punctuation.separator.key-value.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.other.directive.argument.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>directives.sphinx</string>
					<key>match</key>
					<string>(\.\.)(?:\|.*\|)?\s(.*)(::)\s*(.*)$</string>
					<key>name</key>
					<string>entity.directive.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>directives</string>
					<key>match</key>
					<string>(\.\.)\s[A-z][A-z0-9-_]+(::)\s*$</string>
					<key>name</key>
					<string>meta.other.directive.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.field.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.field.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>field list</string>
					<key>match</key>
					<string>(:)[A-z][A-z0-9\-=\s\t_]*(:)</string>
					<key>name</key>
					<string>entity.field.list.name.sphinx.doc</string>
				</dict>
			</array>
		</dict>
		<key>heading</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.sphinx.doc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^(=|-|~|`|#|"|\^|\+|\*){3,}$){1,1}?</string>
					<key>name</key>
					<string>markup.heading.sphinx.doc</string>
				</dict>
			</array>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>strong emphasis</string>
					<key>match</key>
					<string>(\*\*)[^*]+(\*\*)</string>
					<key>name</key>
					<string>markup.bold.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>emphasis</string>
					<key>match</key>
					<string>(\*)\w[^*]\w+(\*)</string>
					<key>name</key>
					<string>markup.italic.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.substitution.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>substitution</string>
					<key>match</key>
					<string>(\|)[^|]+(\|_{0,2})</string>
					<key>name</key>
					<string>markup.underline.substitution.sphinx.doc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>``</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>inline literal</string>
					<key>end</key>
					<string>``</string>
					<key>name</key>
					<string>markup.raw.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.intepreted.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>intepreted text</string>
					<key>match</key>
					<string>(`)[^`]+(`)(?!_)</string>
					<key>name</key>
					<string>markup.other.command.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.table.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>table</string>
					<key>match</key>
					<string>\+-[+-]+</string>
					<key>name</key>
					<string>markup.other.table.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.table.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>table</string>
					<key>match</key>
					<string>\+=[+=]+</string>
					<key>name</key>
					<string>markup.other.table.sphinx.doc</string>
				</dict>
			</array>
		</dict>
		<key>links</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.punctuation.definition.field.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.domain.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.punctuation.definition.field.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.type.cross.reference.sphinx.doc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.punctuation.definition.field.sphinx.doc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.punctuation.definition.link.sphinx.doc</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.sphinx.doc</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>string.punctuation.definition.link.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>:domain:links:`...`_ </string>
					<key>match</key>
					<string>(?:(:)([\w\.\-_]+))?(:)([^:]+)(:)(`)([^&lt;]+?)(`)</string>
					<key>name</key>
					<string>meta.link.cross.reference.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.punctuation.definition.link.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.punctuation.definition.string.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.punctuation.separator.key-value.sphinx.doc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>replacement</string>
					<key>match</key>
					<string>(\.\.)\s+(_)([\w\s\-]+)(:)\s+(.*)</string>
					<key>name</key>
					<string>meta.link.reference.def.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>links `...`_ or `...`__</string>
					<key>match</key>
					<string>\b(\w+)(_)\b</string>
					<key>name</key>
					<string>meta.link.reference</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>links `...`_ or `...`__</string>
					<key>match</key>
					<string>(`)([\w\s]+)(`_)</string>
					<key>name</key>
					<string>meta.link.reference</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.location.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.sphinx.doc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.location.sphinx.doc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>links `...`_ </string>
					<key>match</key>
					<string>(`)([\w\s]+)\s+(&lt;)(.*?)(&gt;)(`_)</string>
					<key>name</key>
					<string>meta.link.inline.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>string.other.footnote.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>replacement</string>
					<key>match</key>
					<string>^(\.\.)\s+((\[)(((#?)[^]]*?)|\*)(\]))\s+(.*)</string>
					<key>name</key>
					<string>meta.link.footnote.def.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>footnote reference: [0]_</string>
					<key>match</key>
					<string>((\[)[0-9]+(\]))(_)</string>
					<key>name</key>
					<string>meta.link.footnote.numeric.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>footnote reference [#]_ or [#foo]_</string>
					<key>match</key>
					<string>((\[#)[A-z0-9_]*(\]))(_)</string>
					<key>name</key>
					<string>meta.link.footnote.auto.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.footnote.link.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>footnote reference [*]_</string>
					<key>match</key>
					<string>((\[)\*(\]))(_)</string>
					<key>name</key>
					<string>meta.link.footnote.symbol.auto.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.citation.link.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.other.citation.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>replacement</string>
					<key>match</key>
					<string>^(\.\.)\s+((\[)[A-z][A-z0-9]*(\]))(_)\s+(.*)</string>
					<key>name</key>
					<string>meta.link.citation.def.sphinx.doc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.citation.link.sphinx.doc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>citation reference</string>
					<key>match</key>
					<string>((\[)[A-z][A-z0-9_-]*(\]))(_)</string>
					<key>name</key>
					<string>meta.link.citation.sphinx.doc</string>
				</dict>
			</array>
		</dict>
		<key>raw</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?!:)([ \t]*).*?((::))</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.raw.sphinx.doc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.sphinx.doc</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>verbatim blocks</string>
					<key>end</key>
					<string>^(?=\1[^\s]+)</string>
					<key>name</key>
					<string>meta.raw.block.sphinx.doc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.+</string>
							<key>name</key>
							<string>markup.raw.sphinx.doc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>directives</string>
					<key>match</key>
					<string>::</string>
					<key>name</key>
					<string>meta.startraw.sphinx.doc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.restructuredtext.sphinx.doc</string>
	<key>uuid</key>
	<string>62DA9AD6-36E1-4AB7-BB87-E933AD9FD1A8</string>
</dict>
</plist>
