<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf.py</string>
	</array>
	<key>name</key>
	<string>Sphinx Conf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sphinx.conf</string>
	<key>uuid</key>
	<string>753CEAE7-8E61-438D-B698-1FBC4FEC66BC</string>
</dict>
</plist>
