<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>handles the Jinja template style used by Sphinx</string>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\{%-? (block|macro|if|for)|\{#)</string>
	<key>foldingStopMarker</key>
	<string>(\{%-? end(block|macro|if|for)|#\})</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Sphinx Template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment_structure</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable_print</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section_punctuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section_structure</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment_structure</key>
		<dict>
			<key>begin</key>
			<string>\{#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>comment.sphinx.doc.template</string>
			<key>end</key>
			<string>#\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_structure</string>
				</dict>
			</array>
		</dict>
		<key>control_keywords</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)\b(if|else|elsif|endif|for|endfor|in|not)\b</string>
		</dict>
		<key>control_structure</key>
		<dict>
			<key>begin</key>
			<string>\b(if|for)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end\1)</string>
			<key>name</key>
			<string>meta.section.control.sphinx.doc.template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#section_structure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_structure</string>
				</dict>
			</array>
		</dict>
		<key>other_keywords</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(set|include|extends|==)\b</string>
		</dict>
		<key>section_punctuation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.sphinx.doc.template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{%-?)|(-?%\})</string>
		</dict>
		<key>section_structure</key>
		<dict>
			<key>begin</key>
			<string>\b(macro|block)\b\s*([^-%=]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.section.begin.sphinx.doc.template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end\1)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.section.end.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.section.sphinx.doc.template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable_print</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_structure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section_punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section_structure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_keywords</string>
				</dict>
			</array>
		</dict>
		<key>section_variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sphinx.doc.template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(set) ([^\s]+)\s*={1,2}</string>
		</dict>
		<key>variable_print</key>
		<dict>
			<key>begin</key>
			<string>(\{\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.variable.print.begin.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.variable.print.sphinx.doc.template</string>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.variable.print.end.sphinx.doc.template</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.restructuredtext.sphinx.doc.template</string>
	<key>uuid</key>
	<string>5C9E7439-3942-4430-8794-79B29F66C3D1</string>
</dict>
</plist>
